#!/bin/bash

userPath=$(wslpath "$(wslvar USERPROFILE)")

case "$1" in
	reload)
		cp ~/dotfiles/glazewm/config.yaml $userPath/.glaze-wm
		if [ $? ]; then
			echo "reload completed..."
			exit 0
		fi
		echo "failed to reload..."
		exit 1
		;;

	*)
		$userPath/scoop/shims/glazewm.exe
		exit 0
		;;
esac

