[general]
import = [
	# "~\\AppData\\Roaming\\alacritty\\themes\\github-dark-tritanopia.toml",
		# "~\\AppData\\Roaming\\alacritty\\themes\\baitong.toml",
	# "~\\AppData\\Roaming\\alacritty\\themes\\catppuccin-macchiato.toml",
		# "~\\AppData\\Roaming\\alacritty\\themes\\nightfly.toml",
	# "~\\AppData\\Roaming\\alacritty\\themes\\cyberdream.toml",
	# "~\\AppData\\Roaming\\alacritty\\themes\\tokyo-night.toml",
	"~\\AppData\\Roaming\\alacritty\\themes\\modus-vivendi.toml"
]

[window]

opacity = 0.90

padding = { x = 3, y = 0 }
dynamic_padding = true

decorations = "Full"
decorations_theme_variant = "Dark"

startup_mode = "Maximized"

[font]

normal.family = "CaskaydiaMono Nerd Font"
bold.family = "CaskaydiaCove Nerd Font"
italic.family = "CaskaydiaMono Nerd Font Mono"
bold_italic.family = "CaskaydiaCove Nerd Font"

size = 12

[terminal]
[terminal.shell]
args = ["--cd ~"]
program = 'C:\Windows\System32\wsl.exe'

