#!/bin/bash

userPath=$(wslpath "$(wslvar USERPROFILE)")

case "$1" in
	start)
		$userPath/scoop/shims/komorebic.exe 'start' '--whkd' > /dev/null 2>&1
		exit 0
		;;

	stop)
		$userPath/scoop/shims/komorebic.exe 'stop'
		exit 0
		;;

	state)
		$userPath/scoop/shims/komorebic.exe 'state'
		exit 0
		;;

	reload)
		cp ~/dotfiles/komorebie/komorebi.json $userPath
		if [ $? ]; then
			echo "reload completed..."
			exit 0
		fi
		echo "failed to reload..."
		exit 1
		;;

	*)
		exit 1
		;;
esac

